// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenJjnPLn8bmPMtbhF8Fmacj2wJj2HLas',
    appId: '1:714209090598:web:6a9a8bcc650c3f59be5ae7',
    messagingSenderId: '714209090598',
    projectId: 'chromosome-app-d6167',
    authDomain: 'chromosome-app-d6167.firebaseapp.com',
    storageBucket: 'chromosome-app-d6167.firebasestorage.app',
    measurementId: 'G-7YBV1DHY95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUMvywiM7_3Aoa1nZxX-HkmQ1HVwdoVzM',
    appId: '1:714209090598:android:f217b80f5e879aebbe5ae7',
    messagingSenderId: '714209090598',
    projectId: 'chromosome-app-d6167',
    storageBucket: 'chromosome-app-d6167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJI3bmiaOWLUACQiRKfU0p6ovxjm50OE',
    appId: '1:714209090598:ios:06c635638143da48be5ae7',
    messagingSenderId: '714209090598',
    projectId: 'chromosome-app-d6167',
    storageBucket: 'chromosome-app-d6167.firebasestorage.app',
    iosBundleId: 'com.example.medcoreCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJI3bmiaOWLUACQiRKfU0p6ovxjm50OE',
    appId: '1:714209090598:ios:06c635638143da48be5ae7',
    messagingSenderId: '714209090598',
    projectId: 'chromosome-app-d6167',
    storageBucket: 'chromosome-app-d6167.firebasestorage.app',
    iosBundleId: 'com.example.medcoreCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCenJjnPLn8bmPMtbhF8Fmacj2wJj2HLas',
    appId: '1:714209090598:web:2be6d2ab7a5d4100be5ae7',
    messagingSenderId: '714209090598',
    projectId: 'chromosome-app-d6167',
    authDomain: 'chromosome-app-d6167.firebaseapp.com',
    storageBucket: 'chromosome-app-d6167.firebasestorage.app',
    measurementId: 'G-4B68WWRZV4',
  );
}
