# -*- coding: utf-8 -*-
"""Copy of ChromosomeSegmentationPipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdyS1GYsMjvWANtNv61eUG5u07k7lxPV
"""

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  PIPELINE NST HOÀN CHỈNH v2 + VERIFY JSON + KARYOGRAM CHUẨN Y KHOA       ║
# ║  Output 1: Karyogram PNG (chuẩn Denver, có khoanh đỏ/mũi tên bất thường) ║
# ║  Output 2: JSON vị trí + loại NST trên ảnh gốc                           ║
# ║  Output 3: Ảnh Verify tọa độ JSON khớp ảnh gốc                           ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# ── 0. CÀI GÓI ──────────────────────────────────────────────────────────────
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "stardist", "csbdeep", "gputools", "pyopencl",
                "ultralytics", "segmentation-models-pytorch",
                "timm", "scipy"], check=False)

# ── 1. MOUNT DRIVE ───────────────────────────────────────────────────────────
from google.colab import drive
try:
    drive.flush_and_unmount()
except Exception:
    pass
import os
os.system("rm -rf /content/drive")
drive.mount("/content/drive")

# ── 2. IMPORT ────────────────────────────────────────────────────────────────
import cv2, json, warnings, random as _random
warnings.filterwarnings("ignore")
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from pathlib import Path

import torch
import torch.nn.functional as F
from PIL import Image, ImageDraw, ImageFont
from torchvision import transforms
import segmentation_models_pytorch as smp
from ultralytics import YOLO
import timm
import albumentations as A
from albumentations.pytorch import ToTensorV2

from stardist.models import StarDist2D
from csbdeep.utils import normalize as csbdeep_normalize
from scipy.optimize import linear_sum_assignment

import ipywidgets as widgets
from IPython.display import display, clear_output
from google.colab import files as colab_files

# ── 3. PATHS ─────────────────────────────────────────────────────────────────
BG_MODEL_PATH       = "/content/drive/MyDrive/Training_Model_buildingclusters/models/bg_separation.pth"
DETECT_MODEL_PATH   = "/content/drive/MyDrive/Training_Model_buildingclusters/models/detect_best.pt"
CLASSIFIER_PATH     = "/content/drive/MyDrive/Training_Model_buildingclusters/classifier/best_classifier.pth"
STARDIST_MODEL_DIR  = "/content/drive/MyDrive/training_overlaping_seg/stardist_model"
STARDIST_MODEL_NAME = "stardist_chromosome"
OUTPUT_DIR          = "/content/drive/MyDrive/Training_Model_buildingclusters/pipeline_output"
INPUT_DIR           = "/content/drive/MyDrive/Training_Model_buildingclusters/Autokary2.0/test_labelme"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── 4. CONFIG ─────────────────────────────────────────────────────────────────
BG_IMG_SIZE  = 512
BG_THRESHOLD = 0.5
BG_MORPH     = 5
DETECT_CONF  = 0.25
DETECT_IOU   = 0.45
MIN_CHR_AREA = 500
NUM_CLASSES  = 24
IMG_SIZE_CLS = 128
DEVICE       = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ── 5. LOAD MODELS ────────────────────────────────────────────────────────────
print("🔍 Kiểm tra & load models...")

def load_bg_model(path):
    m  = smp.Unet(encoder_name="mit_b5", encoder_weights=None, in_channels=3, classes=1)
    ck = torch.load(path, map_location=DEVICE)
    sd = ck["state_dict"] if isinstance(ck, dict) and "state_dict" in ck else ck
    m.load_state_dict(sd); m.to(DEVICE); m.eval()
    return m

bg_model       = load_bg_model(BG_MODEL_PATH)
detect_model   = YOLO(DETECT_MODEL_PATH)
stardist_model = StarDist2D(None, name=STARDIST_MODEL_NAME, basedir=STARDIST_MODEL_DIR)
cls_model      = timm.create_model("efficientnet_b3", pretrained=False, num_classes=NUM_CLASSES)
cls_model.load_state_dict(torch.load(CLASSIFIER_PATH, map_location=DEVICE))
cls_model.to(DEVICE).eval()
print(f"✅ All models loaded | device={DEVICE}\n")

# ── 6. CLASS HELPERS ──────────────────────────────────────────────────────────
def idx_to_name(idx):
    if idx <= 21: return str(idx + 1)
    return "X" if idx == 22 else "Y"

CLASS_NAMES = [idx_to_name(i) for i in range(NUM_CLASSES)]

# ── 7. BACKGROUND REMOVAL ─────────────────────────────────────────────────────
bg_tf = transforms.Compose([
    transforms.Resize((BG_IMG_SIZE, BG_IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
])

def remove_background(img_path):
    pil  = Image.open(img_path).convert("RGB")
    W, H = pil.size
    t    = bg_tf(pil).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        out = bg_model(t)
    mask = torch.sigmoid(out).squeeze().cpu().numpy()
    mask = (mask > BG_THRESHOLD).astype(np.uint8) * 255
    mask = np.array(Image.fromarray(mask).resize((W, H), Image.Resampling.LANCZOS))
    k    = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (BG_MORPH, BG_MORPH))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, k)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN,  k)
    mask = (mask > 127).astype(np.uint8) * 255
    orig = np.array(pil)
    res  = np.zeros_like(orig)
    res[mask > 127] = orig[mask > 127]
    return cv2.cvtColor(res, cv2.COLOR_RGB2BGR)

# ── 8. UTILS ──────────────────────────────────────────────────────────────────
def keep_largest(mask):
    nl, labels, stats, _ = cv2.connectedComponentsWithStats(mask, connectivity=8)
    if nl <= 1: return mask
    lg = 1 + np.argmax(stats[1:, cv2.CC_STAT_AREA])
    r  = np.zeros_like(mask); r[labels == lg] = 255
    return r

# ── 9. STARDIST SEPARATION ────────────────────────────────────────────────────
def _watershed_fallback(crop_bgr):
    gray = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2GRAY)
    _, thr = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)
    k  = np.ones((3,3), np.uint8)
    op = cv2.morphologyEx(thr, cv2.MORPH_OPEN, k, iterations=2)
    bg = cv2.dilate(op, k, iterations=3)
    dist = cv2.distanceTransform(op, cv2.DIST_L2, 5)
    if dist.max() == 0: return [thr]
    _, fg  = cv2.threshold(dist, 0.6*dist.max(), 255, 0)
    fg     = np.uint8(fg)
    unk    = cv2.subtract(bg, fg)
    ret, markers = cv2.connectedComponents(fg)
    markers = markers+1; markers[unk==255] = 0
    markers = cv2.watershed(crop_bgr.copy(), markers)
    res = []
    for i in range(2, ret+1):
        m = (markers==i).astype(np.uint8)*255
        cnts,_ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if cnts and cv2.contourArea(max(cnts, key=cv2.contourArea)) >= MIN_CHR_AREA:
            res.append(m)
    return res if res else [thr]

def sep_clustered(crop_bgr):
    gray  = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2GRAY)
    img_n = csbdeep_normalize(gray.astype(np.float32)/255.0, 1, 99.8)
    try:
        labels, _ = stardist_model.predict_instances(img_n)
    except Exception:
        return _watershed_fallback(crop_bgr)
    if labels.max() == 0:
        return _watershed_fallback(crop_bgr)
    k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
    masks = []
    for i in range(1, int(labels.max())+1):
        m = (labels==i).astype(np.uint8)*255
        if m.sum()//255 < MIN_CHR_AREA: continue
        m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, k)
        masks.append(m)
    return masks if masks else _watershed_fallback(crop_bgr)

# ── 10. CLASSIFY (batch) ──────────────────────────────────────────────────────
cls_tf = A.Compose([
    A.LongestMaxSize(max_size=IMG_SIZE_CLS),
    A.PadIfNeeded(IMG_SIZE_CLS, IMG_SIZE_CLS,
                  border_mode=cv2.BORDER_CONSTANT, value=0),
    A.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
    ToTensorV2(),
])

def classify_all(crop_list, batch_size=64):
    all_probs, buf = [], []
    for i, crop in enumerate(crop_list):
        img = cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)
        buf.append(cls_tf(image=img)["image"])
        if len(buf) == batch_size or i == len(crop_list)-1:
            batch = torch.stack(buf).to(DEVICE)
            with torch.no_grad():
                p = F.softmax(cls_model(batch), dim=1).cpu().numpy()
            all_probs.append(p); buf = []
    return np.vstack(all_probs)   # (N, 24)

# ── 11. HUNGARIAN ASSIGNMENT ──────────────────────────────────────────────────
def assign_pairs(probs, crop_list):
    N = len(crop_list)
    if N == 0: return {n: [] for n in CLASS_NAMES}, []

    y_sum = probs[:, 23].sum()
    sex   = "male" if y_sum > 0.3 else "female"

    exp = {str(i): 2 for i in range(1, 23)}
    exp["X"] = 2 if sex == "female" else 1
    exp["Y"] = 0 if sex == "female" else 1

    slots = []
    for name in CLASS_NAMES:
        for _ in range(max(1, exp.get(name, 1))):
            slots.append(name)
    M = len(slots)

    slot_ci = [CLASS_NAMES.index(s) for s in slots]
    cost    = np.zeros((N, M), dtype=np.float64)
    for j, ci in enumerate(slot_ci):
        cost[:, j] = -np.log(probs[:, ci] + 1e-9)
    if N > M:
        cost = np.hstack([cost, np.full((N, N-M), 100.0)])

    row_ind, col_ind = linear_sum_assignment(cost)
    assignment = {n: [] for n in CLASS_NAMES}
    unassigned = []
    for r, c in zip(row_ind, col_ind):
        if c < M: assignment[slots[c]].append(crop_list[r])
        else:     unassigned.append(crop_list[r])
    return assignment, unassigned

# ── 12. ORIENT ────────────────────────────────────────────────────────────────
def orient_chromosome(crop_bgr):
    gray = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2GRAY)
    _, mask = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)
    pts = np.column_stack(np.where(mask > 0)).astype(np.float32)
    if len(pts) < 10: return crop_bgr

    mean = pts.mean(axis=0)
    _, _, vt = np.linalg.svd(pts - mean, full_matrices=False)
    angle_deg    = np.degrees(np.arctan2(vt[0][1], vt[0][0]))
    rotate_angle = angle_deg - 90.0

    H, W = crop_bgr.shape[:2]
    cx, cy = W/2, H/2
    M_rot  = cv2.getRotationMatrix2D((cx, cy), -rotate_angle, 1.0)
    cos_a, sin_a = abs(M_rot[0,0]), abs(M_rot[0,1])
    nW = int(H*sin_a + W*cos_a); nH = int(H*cos_a + W*sin_a)
    M_rot[0,2] += nW/2-cx; M_rot[1,2] += nH/2-cy
    rotated = cv2.warpAffine(crop_bgr, M_rot, (nW,nH),
                              flags=cv2.INTER_LANCZOS4,
                              borderMode=cv2.BORDER_CONSTANT, borderValue=255)

    # Crop tight
    g2 = cv2.cvtColor(rotated, cv2.COLOR_BGR2GRAY)
    _, m2 = cv2.threshold(g2, 240, 255, cv2.THRESH_BINARY_INV)
    ys, xs = np.where(m2 > 0)
    if len(xs) == 0: return rotated
    pad = 4
    x1c = max(0, xs.min()-pad); y1c = max(0, ys.min()-pad)
    x2c = min(rotated.shape[1], xs.max()+pad)
    y2c = min(rotated.shape[0], ys.max()+pad)
    cropped = rotated[y1c:y2c, x1c:x2c]

    # Centromere: min-width scan → p-arm lên trên
    g3 = cv2.cvtColor(cropped, cv2.COLOR_BGR2GRAY)
    _, m3 = cv2.threshold(g3, 240, 255, cv2.THRESH_BINARY_INV)
    H3 = m3.shape[0]
    row_w = []
    for r in range(H3):
        nz = np.where(m3[r] > 0)[0]
        row_w.append(nz[-1]-nz[0]+1 if len(nz)>1 else 0)
    row_w  = np.array(row_w, dtype=np.float32)
    ks     = max(3, H3//20)
    smooth = np.convolve(row_w, np.ones(ks)/ks, mode="same")
    margin = max(1, H3//10)
    region = smooth[margin:H3-margin]
    if len(region) > 0:
        centro = int(region.argmin()) + margin
        if centro > H3/2:
            cropped = cv2.flip(cropped, 0)
    return cropped

# ── 13. KARYOGRAM LAYOUT (chuẩn ảnh mẫu, có đóng khung đỏ bất thường) ────────
# Thêm "gap" để tạo khoảng trống phân tách các nhóm (Group A -> G) theo chuẩn Denver
ISCN_ROWS = [
    ["1","2","3", "gap", "4","5"],
    ["6","7","8", "gap", "9","10","11","12"],
    ["13","14","15", "gap", "16","17","18"],
    ["19","20", "gap", "21","22", "gap", "X","Y"],
]

# Tỉ lệ chiều cao tương đối giữa các cặp NST (chuẩn cytogenetic)
CHR_REL_HEIGHT = {
    "1":1.00,"2":0.95,"3":0.82,"4":0.76,"5":0.72,
    "6":0.68,"7":0.63,"8":0.59,"9":0.57,"10":0.55,
    "11":0.54,"12":0.53,"13":0.48,"14":0.45,"15":0.43,
    "16":0.41,"17":0.39,"18":0.37,"19":0.31,"20":0.30,
    "21":0.27,"22":0.26,"X":0.58,"Y":0.30,
}
BASE_CHR_HEIGHT = 220   # px height của NST số 1 (lớn nhất)

def make_chr_img(crop_bgr, target_h, white_bg=True):
    if crop_bgr is None or crop_bgr.size == 0:
        return np.full((target_h, max(1, target_h//4), 3), 255, dtype=np.uint8)

    gray = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2GRAY)
    _, fg_mask = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY_INV)

    ih, iw = gray.shape[:2]
    if ih == 0: return np.full((target_h, 1, 3), 255, dtype=np.uint8)
    scale = target_h / ih
    nw    = max(1, int(iw * scale))
    gray_r   = cv2.resize(gray,    (nw, target_h), interpolation=cv2.INTER_LANCZOS4)
    mask_r   = cv2.resize(fg_mask, (nw, target_h), interpolation=cv2.INTER_NEAREST)

    canvas = np.full((target_h, nw, 3), 255, dtype=np.uint8)
    chr_bgr = cv2.cvtColor(gray_r, cv2.COLOR_GRAY2BGR)
    canvas[mask_r > 127] = chr_bgr[mask_r > 127]
    return canvas

def build_karyogram(assignment, output_path, title=""):
    PAIR_GAP   = 6    # px giữa các NST trong cùng 1 cặp
    COL_GAP    = 36   # px giữa các cặp NST
    GROUP_GAP  = 70   # px khoảng trống giữa các nhóm (thay cho "gap")
    ROW_GAP    = 55   # px giữa các hàng
    MARGIN_X   = 50
    MARGIN_Y   = 50
    LABEL_H    = 25
    TITLE_H    = 36 if title else 0

    try:
        f_label = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 15)
        f_title = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 18)
    except Exception:
        f_label = f_title = ImageFont.load_default()

    # ── Build từng pair block ──────────────────────────────────────────────
    rows_blocks = []
    for row_names in ISCN_ROWS:
        row = []
        for name in row_names:
            if name == "gap":
                block = np.full((10, GROUP_GAP, 3), 255, dtype=np.uint8)
                row.append((name, block, 10))
                continue

            target_h = max(20, int(BASE_CHR_HEIGHT * CHR_REL_HEIGHT.get(name, 0.5)))
            crops    = assignment.get(name, [])

            # Giữ TẤT CẢ NST (Hỗ trợ 3 NST nếu bị Down), thay vì cắt [:2]
            oriented_crops = [orient_chromosome(c) for c in crops]

            # Khung nét đứt nếu thiếu NST
            while len(oriented_crops) < 2:
                blank = np.full((target_h, max(1, target_h//5), 3), 255, dtype=np.uint8)
                cv2.rectangle(blank, (0,0), (blank.shape[1]-1, blank.shape[0]-1), (210,210,210), 1)
                oriented_crops.append(blank)

            imgs = [make_chr_img(c, target_h) for c in oriented_crops]
            tw   = sum(img.shape[1] for img in imgs) + PAIR_GAP * (len(imgs) - 1)

            block = np.full((target_h, tw, 3), 255, dtype=np.uint8)
            cx = 0
            for img in imgs:
                block[:, cx:cx+img.shape[1]] = img
                cx += img.shape[1] + PAIR_GAP
            row.append((name, block, target_h))
        rows_blocks.append(row)

    # ── Tính kích thước canvas ─────────────────────────────────────────────
    row_widths = []
    for row in rows_blocks:
        w = sum(b.shape[1] for _,b,_ in row) + COL_GAP*(len(row)-1)
        row_widths.append(w)

    canvas_w = max(row_widths) + 2*MARGIN_X
    canvas_h = MARGIN_Y + TITLE_H

    row_heights = []
    for row in rows_blocks:
        hs = [ph for n, _, ph in row if n != "gap"]
        rh = max(hs) if hs else 0
        row_heights.append(rh)
        canvas_h += rh + LABEL_H + ROW_GAP
    canvas_h += MARGIN_Y

    canvas = np.full((canvas_h, canvas_w, 3), 255, dtype=np.uint8)
    pil    = Image.fromarray(canvas)
    draw   = ImageDraw.Draw(pil)

    if title:
        draw.text((MARGIN_X, MARGIN_Y), title, fill=(30,30,30), font=f_title)

    # ── Vẽ từng hàng ──────────────────────────────────────────────────────
    y_cur = MARGIN_Y + TITLE_H
    for row_idx, row in enumerate(rows_blocks):
        row_w  = sum(b.shape[1] for _,b,_ in row) + COL_GAP*(len(row)-1)
        x_start= (canvas_w - row_w)//2
        row_h  = row_heights[row_idx]

        x_cur = x_start
        for name, block, pair_h in row:
            bh, bw = block.shape[:2]

            if name == "gap":
                x_cur += bw + COL_GAP
                continue

            # Bottom-align các NST trên cùng hàng
            y_paste = y_cur + (row_h - bh)

            canvas_arr = np.array(pil)
            canvas_arr[y_paste:y_paste+bh, x_cur:x_cur+bw] = block
            pil  = Image.fromarray(canvas_arr)
            draw = ImageDraw.Draw(pil)

            n_c = len(assignment.get(name, []))

            # Detect bất thường (Khác 2 chiếc cho NST thường, hoặc >2 cho giới tính)
            is_anomalous = (name not in ["X", "Y"] and n_c != 2) or (name in ["X", "Y"] and n_c > 2)
            color = (220, 30, 30) if is_anomalous else (40, 40, 40)

            # Vẽ Box Đỏ + Mũi tên (Như ảnh mẫu) nếu có dị bội
            if is_anomalous:
                pad = 8
                box_x1, box_y1 = x_cur - pad, y_paste - pad
                box_x2, box_y2 = x_cur + bw + pad, y_paste + bh + pad
                # Vẽ Box
                draw.rectangle([(box_x1, box_y1), (box_x2, box_y2)], outline=(220,30,30), width=2)

                # Vẽ Mũi Tên Đỏ chỉ vào góc trên bên phải
                ax_s, ay_s = box_x2 + 25, box_y1 - 25
                ax_e, ay_e = box_x2 + 4, box_y1 - 4
                draw.line([(ax_s, ay_s), (ax_e, ay_e)], fill=(220,30,30), width=3)
                draw.polygon([(ax_e, ay_e), (ax_e+12, ay_e-2), (ax_e+2, ay_e-12)], fill=(220,30,30))

            lx = x_cur + bw//2
            ly = y_cur + row_h + 8
            draw.text((lx, ly), name, fill=color, font=f_label, anchor="mt")

            x_cur += bw + COL_GAP

        y_cur += row_h + LABEL_H + ROW_GAP

    draw.rectangle([(1,1),(canvas_w-2, canvas_h-2)], outline=(220,220,220), width=1)

    canvas_final = np.array(pil)
    cv2.imwrite(output_path, cv2.cvtColor(canvas_final, cv2.COLOR_RGB2BGR))
    return canvas_final   # RGB

# ── 14. JSON OUTPUT ───────────────────────────────────────────────────────────
def build_json(chr_records, img_path, img_shape, output_path):
    H, W = img_shape[:2]
    result = {
        "image_path"  : str(img_path),
        "image_width" : W,
        "image_height": H,
        "total_chromosomes": len(chr_records),
        "chromosomes" : chr_records,
    }
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    return result

def draw_json_overlay(orig_img_path, json_path, output_path):
    img = cv2.imread(orig_img_path)
    if img is None:
        return None

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Lỗi đọc JSON: {e}")
        return img

    for chr_data in data.get("chromosomes", []):
        polygon = chr_data.get("polygon_on_original", [])
        if polygon:
            pts = np.array(polygon, np.int32)
            pts = pts.reshape((-1, 1, 2))
            cv2.polylines(img, [pts], isClosed=True, color=(0, 255, 0), thickness=2)

        bbox = chr_data.get("bbox_on_original", {})
        if bbox:
            x1, y1 = bbox.get("x1", 0), bbox.get("y1", 0)
            x2, y2 = bbox.get("x2", 0), bbox.get("y2", 0)
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 255), 1)

            name = chr_data.get("chr_name", "unk")
            cv2.putText(img, name, (x1, max(y1 - 5, 0)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 255), 1)

    cv2.imwrite(output_path, img)
    return img

# ── 15. PIPELINE CHÍNH ────────────────────────────────────────────────────────
def run_pipeline(img_path):
    img_name = Path(img_path).stem
    print(f"\n{'─'*60}")
    print(f"  📸 {Path(img_path).name}")
    print(f"{'─'*60}")

    # [1/5] Tách nền
    print("  [1/5] Tách nền...")
    img_bg   = remove_background(img_path)
    orig_bgr = cv2.imread(img_path)
    if orig_bgr is None:
        orig_bgr = img_bg.copy()
    H, W = img_bg.shape[:2]

    # [2/5] Detect
    print("  [2/5] Detect single/clustered...")
    det = detect_model(img_bg, conf=DETECT_CONF, iou=DETECT_IOU, verbose=False)[0]
    if det.boxes is None or len(det.boxes) == 0:
        print("  ⚠️  Không detect được gì!"); return 0

    # [3/5] Tách NST
    print("  [3/5] Tách NST (StarDist)...")
    viz_detect    = img_bg.copy()
    raw_chrs      = []   # list of {mask, ox, oy, det_class}
    counts        = {"single": 0, "clustered": 0}
    COLORS        = {"single": (74,158,255), "clustered": (107,107,255)}

    for box in det.boxes:
        cls_name    = ["single","clustered"][int(box.cls)]
        x1,y1,x2,y2= map(int, box.xyxy[0].tolist())
        conf        = float(box.conf)
        x1c,y1c     = max(0,x1), max(0,y1)
        x2c,y2c     = min(W,x2), min(H,y2)
        if x2c<=x1c or y2c<=y1c: continue

        crop  = img_bg[y1c:y2c, x1c:x2c].copy()
        color = COLORS[cls_name]

        if cls_name == "single":
            gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
            _, mask = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)
            mask = keep_largest(mask)
            raw_chrs.append({"mask":mask,"ox":x1c,"oy":y1c,"det_cls":cls_name})
        else:
            for m in sep_clustered(crop):
                raw_chrs.append({"mask":m,"ox":x1c,"oy":y1c,"det_cls":cls_name})

        # Vẽ bbox
        cv2.rectangle(viz_detect, (x1c,y1c), (x2c,y2c), color, 2)
        lbl = f"{cls_name} {conf:.2f}"
        fs  = max(0.4, W/1500)
        (tw,th),_ = cv2.getTextSize(lbl, cv2.FONT_HERSHEY_SIMPLEX, fs, 1)
        cv2.rectangle(viz_detect, (x1c,y1c-th-6),(x1c+tw+6,y1c), color, -1)
        cv2.putText(viz_detect, lbl, (x1c+3,y1c-3),
                    cv2.FONT_HERSHEY_SIMPLEX, fs, (0,0,0), 1)
        counts[cls_name] += 1

    # [4/5] Crop + Classify + Build records
    print(f"  [4/5] Classify {len(raw_chrs)} NST...")
    crop_dir = os.path.join(OUTPUT_DIR, f"crops_{img_name}")
    os.makedirs(crop_dir, exist_ok=True)

    all_chr_crops = []
    chr_meta      = []   # metadata tương ứng với từng crop
    viz_result    = np.zeros((H,W,3), dtype=np.uint8)
    chr_idx       = 0

    for rec in raw_chrs:
        mask, ox, oy = rec["mask"], rec["ox"], rec["oy"]
        if mask is None or np.sum(mask) < MIN_CHR_AREA: continue
        ys, xs = np.where(mask > 0)
        if len(xs) == 0: continue

        mx1,my1,mx2,my2 = xs.min(),ys.min(),xs.max(),ys.max()
        ax1 = ox + mx1; ay1 = oy + my1
        ax2 = min(ox+mx2, W-1); ay2 = min(oy+my2, H-1)

        chr_crop = img_bg[ay1:ay2+1, ax1:ax2+1].copy()
        chr_mask = mask[my1:my2+1, mx1:mx2+1]
        result_chr = cv2.bitwise_and(chr_crop, chr_crop, mask=chr_mask)
        chr_idx += 1
        cv2.imwrite(os.path.join(crop_dir, f"chr_{chr_idx:03d}.png"), result_chr)

        all_chr_crops.append(result_chr)

        full_mask = np.zeros((H,W), dtype=np.uint8)
        hm,wm = mask.shape
        ye,xe = min(oy+hm,H), min(ox+wm,W)
        full_mask[oy:ye, ox:xe] = mask[:ye-oy, :xe-ox]
        cnts,_ = cv2.findContours(full_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        polygon = cnts[0].reshape(-1,2).tolist() if cnts else []

        chr_meta.append({
            "crop_idx"  : chr_idx,
            "bbox_orig" : [int(ax1), int(ay1), int(ax2), int(ay2)],
            "area_px"   : int(np.sum(mask>0)),
            "det_cls"   : rec["det_cls"],
            "polygon"   : polygon,
        })

        color_v = np.random.randint(80,255,3).tolist()
        viz_result[full_mask==255] = color_v

    if not all_chr_crops:
        print("  ⚠️  Không có crop NST!"); return 0

    probs      = classify_all(all_chr_crops)
    assignment, unassigned = assign_pairs(probs, all_chr_crops)

    crop_to_class = {}
    for cls_name, crops_in_cls in assignment.items():
        for c in crops_in_cls:
            for j, orig_crop in enumerate(all_chr_crops):
                if orig_crop is c:
                    crop_to_class[j] = cls_name
                    break

    chr_records = []
    for j, meta in enumerate(chr_meta):
        cls_name_j = crop_to_class.get(j, "unknown")
        conf_j     = float(probs[j, CLASS_NAMES.index(cls_name_j)]
                           if cls_name_j in CLASS_NAMES else 0.0)
        chr_records.append({
            "id"          : meta["crop_idx"],
            "chr_name"    : cls_name_j,
            "confidence"  : round(conf_j, 4),
            "bbox_on_original": {
                "x1": meta["bbox_orig"][0], "y1": meta["bbox_orig"][1],
                "x2": meta["bbox_orig"][2], "y2": meta["bbox_orig"][3],
            },
            "area_px"     : meta["area_px"],
            "detected_as" : meta["det_cls"],
            "polygon_on_original": meta["polygon"],
        })

    json_path = os.path.join(OUTPUT_DIR, f"result_{img_name}.json")
    build_json(chr_records, img_path, (H,W), json_path)
    print(f"  ✅ JSON saved → {json_path}")

    print("  [+] Tạo ảnh verify tọa độ JSON...")
    verify_json_path = os.path.join(OUTPUT_DIR, f"verify_json_{img_name}.jpg")
    img_verify_json = draw_json_overlay(img_path, json_path, verify_json_path)
    print(f"  ✅ Ảnh test JSON saved → {verify_json_path}")

    # [5/5] Karyogram
    print("  [5/5] Building karyogram...")
    karyo_path = os.path.join(OUTPUT_DIR, f"karyogram_{img_name}.png")
    karyo_rgb  = build_karyogram(assignment, karyo_path, title=img_name)
    print(f"  ✅ Karyogram saved → {karyo_path}")

    anomalies = []
    for name, cl in assignment.items():
        exp = 2 if name not in ("X","Y") else 1
        if len(cl) != exp and cl:
            anomalies.append(f"{name}({len(cl)})")
    if anomalies:
        print(f"  ⚠️  Bất thường (đỏ): {', '.join(anomalies)}")
    if unassigned:
        print(f"  ⚠️  {len(unassigned)} NST không assign")

    # ── Visualize ─────────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(35, 6), facecolor="#0d0d0d")
    gs  = gridspec.GridSpec(1, 6, figure=fig, wspace=0.03)

    panels = [
        (cv2.cvtColor(orig_bgr,   cv2.COLOR_BGR2RGB), "1. Ảnh gốc"),
        (cv2.cvtColor(img_bg,     cv2.COLOR_BGR2RGB), "2. Tách nền"),
        (cv2.cvtColor(viz_detect, cv2.COLOR_BGR2RGB), f"3. Detect  S:{counts['single']} C:{counts['clustered']}"),
        (cv2.cvtColor(viz_result, cv2.COLOR_BGR2RGB), f"4. StarDist — {chr_idx} NST"),
        (cv2.cvtColor(img_verify_json, cv2.COLOR_BGR2RGB) if img_verify_json is not None else np.zeros((H,W,3), dtype=np.uint8), "5. Verify JSON"),
        (karyo_rgb, "6. Karyogram"),
    ]
    for i, (img_rgb, ttl) in enumerate(panels):
        ax = fig.add_subplot(gs[i])
        ax.imshow(img_rgb)
        ax.set_title(ttl, color="white", fontsize=9, pad=5)
        ax.axis("off"); ax.set_facecolor("#0d0d0d")

    overview_path = os.path.join(OUTPUT_DIR, f"overview_{img_name}.jpg")
    plt.savefig(overview_path, dpi=90, bbox_inches="tight", facecolor="#0d0d0d")
    plt.show(); plt.close()

    plt.figure(figsize=(18, 10), facecolor="white")
    plt.imshow(karyo_rgb)
    plt.axis("off")
    plt.title(img_name, fontsize=12, pad=8)
    plt.tight_layout()
    plt.show(); plt.close()

    print(f"\n  ✅ {chr_idx} NST | S:{counts['single']} C:{counts['clustered']}")
    print(f"  📁 crops      → {crop_dir}")
    print(f"  🧬 karyogram  → {karyo_path}")
    print(f"  📄 JSON       → {json_path}")
    print(f"  🖼️ Test JSON  → {verify_json_path}")
    return chr_idx

# ── 16. WIDGET UI ─────────────────────────────────────────────────────────────
mode_drop = widgets.Dropdown(
    options=[
        ("Upload ảnh từ máy tính",       "upload"),
        ("Ảnh test_labelme ngẫu nhiên",  "random"),
        ("Toàn bộ test_labelme",         "all"),
    ],
    value="upload",
    description="Nguồn:",
    layout=widgets.Layout(width="320px"),
)
run_btn = widgets.Button(
    description="▶  Chạy pipeline",
    button_style="success",
    layout=widgets.Layout(width="190px", height="36px"),
)
out_w = widgets.Output()

display(widgets.VBox([
    widgets.HTML("""
    <div style='font-family:monospace;padding:10px 0'>
      <h3 style='margin:0 0 4px'>🧬 NST Pipeline — Full v2 (Chuẩn Denver)</h3>
      <span style='color:#888;font-size:12px'>
        Tách nền → Detect → StarDist → Classify → Karyogram (Khung Đỏ) + JSON
      </span>
    </div>
    """),
    mode_drop,
    widgets.HTML("<hr style='margin:8px 0'>"),
    run_btn, out_w,
]))

def on_run(b):
    with out_w:
        clear_output(wait=True)
        mode = mode_drop.value

        if mode == "upload":
            print("📁 Chọn ảnh gốc...")
            uploaded = colab_files.upload()
            if not uploaded: return
            paths = []
            for name, data in uploaded.items():
                p = f"/content/{name}"
                with open(p, "wb") as f: f.write(data)
                paths.append(p)

        elif mode == "random":
            imgs = (list(Path(INPUT_DIR).rglob("*.png")) +
                    list(Path(INPUT_DIR).rglob("*.jpg")))
            if not imgs:
                print(f"❌ Không tìm thấy ảnh trong {INPUT_DIR}"); return
            paths = [str(_random.choice(imgs))]
            print(f"🎲 {Path(paths[0]).name}")

        else:
            paths  = [str(p) for p in Path(INPUT_DIR).rglob("*.png")]
            paths += [str(p) for p in Path(INPUT_DIR).rglob("*.jpg")]
            paths  = [p for p in paths if not any(
                x in Path(p).name
                for x in ["result_","chr_","karyogram_","overview_","verify_json_"])]
            print(f"📂 {len(paths)} ảnh")

        total = 0
        for i, p in enumerate(paths, 1):
            if len(paths) > 1:
                print(f"\n[{i}/{len(paths)}] {Path(p).name}")
            n = run_pipeline(p)
            if n: total += n

        if len(paths) > 1:
            print(f"\n{'='*52}")
            print(f"🎉 Xong! Tổng {total} NST | Output: {OUTPUT_DIR}")

run_btn.on_click(on_run)